/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Date;
import java.util.List;
import model.Pessoa;
import service.LoginService;
import service.PessoaService;
import service.ServiceFactory;

/**
 *
 * @author PICHAU
 */
public class ListaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaClientes
     */
    public ListaUsuario() {
        initComponents();

        exibir();
    }

    public final void exibir() {
        PessoaService entity = ServiceFactory.getPessoaService();
        LoginService entity3 = ServiceFactory.getLoginService();

        List<Pessoa> pessoa = entity.recuperaPessoa();

        Pessoa p;
        String[][] dados = new String[pessoa.size()][17];

        for (int i = 0; i < pessoa.size(); i++) {

            p = pessoa.get(i);
            dados[i][3] = p.getDataNascimento().toString();
            dados[i][0] = p.getNome();
            dados[i][5] = p.getSexo();
            dados[i][4] = " " + p.getIdade();
            dados[i][1] = p.getCpf();



            String us = entity3.consultaLoginUsuario(p.getIdPessoa());

            dados[i][2] = us;

        }
        tabelaUsuario = new javax.swing.JTable();

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
                dados,
                new String[]{
                    "Nome", "CPF", "Usuario", "Data de Nascimento", "Idade", "Sexo"
                }
        ));

        jScrollPane2.setViewportView(tabelaUsuario);

    }




    private void cadastrar() {

        CadastrarUsuario cad = new CadastrarUsuario();
        getParent().add(cad);
        cad.setVisible(true);
    }

    private void alteraUsuario() {
        if (tabelaUsuario.getSelectedRow() != -1) {
            AlteraUsuario alterar = new AlteraUsuario();
            
            alterar.cpfOld.setText((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 1));
            alterar.cpf.setText((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 1));
            alterar.nome.setText((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 0));
            alterar.sexo.setSelectedItem((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 5));

            if (((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 5)).equals("Feminino")) {
                alterar.sexo.setSelectedIndex(0);
            } else {
                alterar.sexo.setSelectedIndex(1);
            }
            alterar.dataNascimento.setText((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 3));

            Date data;
            String d = (String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 3);
            String[] lista;
            lista = d.split("-");

            alterar.dataNascimento.setText(lista[2] + "/"
                    + lista[1] + "/" + lista[0]);

            PessoaService entity = ServiceFactory.getPessoaService();
            LoginService entity2 = ServiceFactory.getLoginService();

            long idPessoa = entity.idCPF((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 1));
            alterar.usuario.setText(entity2.consultaLoginUsuario(idPessoa));

            getParent().add(alterar);
            alterar.setVisible(true);
        }
    }

    private void excluirUsuario() {
        if (tabelaUsuario.getSelectedRow() != -1) {
            ExcluirUsuario exclui = new ExcluirUsuario();
            exclui.cpf.setText((String) tabelaUsuario.getModel().getValueAt(tabelaUsuario.getSelectedRow(), 1));
            getParent().add(exclui);
            exclui.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        Atualizar = new javax.swing.JButton();
        label1 = new java.awt.Label();
        atualizar = new java.awt.Button();
        usuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Usuário");

        Excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Excluir.setForeground(new java.awt.Color(204, 0, 51));
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        tabelaUsuario.setEnabled(false);
        tabelaUsuario.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(tabelaUsuario);

        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atualizar.setForeground(new java.awt.Color(0, 0, 204));
        Atualizar.setText("Atualizar Usuario");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Lista de Usuarios:");

        atualizar.setLabel("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 204));
        usuario.setText("Cadastrar Usuario");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Atualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        excluirUsuario();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        // TODO add your handling code here:
        alteraUsuario();
    }//GEN-LAST:event_AtualizarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        exibir();
    }//GEN-LAST:event_atualizarActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_usuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Excluir;
    private java.awt.Button atualizar;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables

}
